displayName=RuneHelp
author=jackkennedy7 & shane-roth
description=A plugin to associate your account with RuneHelp, gathering more data to give better inights
tags=
plugins=com.runehelp.RuneHelpPlugin
